name: Deploy Python to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::691595239492:role/GitHub-Lambda_Deploy
        aws-region: ap-southeast-5

    - name: Zip Lambda function
      run: zip -r function.zip .

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name HackathonFunction \
          --zip-file fileb://function.zip
